# Generated by Django 6.0.1 on 2026-02-01 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("constraints", models.TextField(blank=True)),
                ("examples", models.JSONField(blank=True, default=list)),
                ("starter_code_python", models.TextField(blank=True)),
                ("starter_code_javascript", models.TextField(blank=True)),
                ("starter_code_java", models.TextField(blank=True)),
                ("starter_code_cpp", models.TextField(blank=True)),
                ("acceptance_rate", models.FloatField(default=0.0)),
                ("total_submissions", models.IntegerField(default=0)),
                ("total_accepted", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_problems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("approach", models.TextField()),
                ("code", models.TextField()),
                ("language", models.CharField(max_length=50)),
                ("time_complexity", models.CharField(blank=True, max_length=100)),
                ("space_complexity", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solutions",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField()),
                ("expected_output", models.TextField()),
                ("is_sample", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("explanation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["difficulty"], name="problems_pr_difficu_d3b056_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["category"], name="problems_pr_categor_db58d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(fields=["slug"], name="problems_pr_slug_19f4ac_idx"),
        ),
    ]
