# Generated by Django 6.0.1 on 2026-02-01 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python 3"),
                            ("javascript", "JavaScript"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processing", "Processing"),
                            ("Accepted", "Accepted"),
                            ("Wrong Answer", "Wrong Answer"),
                            ("Time Limit Exceeded", "Time Limit Exceeded"),
                            ("Memory Limit Exceeded", "Memory Limit Exceeded"),
                            ("Runtime Error", "Runtime Error"),
                            ("Compilation Error", "Compilation Error"),
                            ("Internal Error", "Internal Error"),
                        ],
                        default="Pending",
                        max_length=30,
                    ),
                ),
                ("runtime", models.IntegerField(blank=True, null=True)),
                ("memory", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("passed_test_cases", models.IntegerField(default=0)),
                ("total_test_cases", models.IntegerField(default=0)),
                ("failed_test_case", models.JSONField(blank=True, null=True)),
                ("judge0_token", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="problems.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="submissions_user_id_7cc934_idx",
                    ),
                    models.Index(
                        fields=["problem", "-created_at"],
                        name="submissions_problem_35c851_idx",
                    ),
                    models.Index(
                        fields=["status"], name="submissions_status_c2b4f2_idx"
                    ),
                ],
            },
        ),
    ]
